### ISSUE TITLE
Add Cloth Config API as hard dependency?

### ISSUE THREAD

**Issue by KisaragiEffective** [shedaniel/AutoConfig#15]
I got bunch of crash when clicked on the correspond mod information, and here is the crash report:
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2020/08/04 23:56
Description: Rendering screen

java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/ConfigEntryBuilder
	at me.sargunvohra.mcmods.autoconfig1u.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:36)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:81)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigScreen(AutoConfig.java:71)
	at technicianlp.reauth.integration.ModMenuIntegration.lambda$getModConfigScreenFactory$0(ModMenuIntegration.java:11)
	at io.github.prospector.modmenu.ModMenu.hasConfigScreenFactory(ModMenu.java:45)
	at io.github.prospector.modmenu.gui.ModsScreen$1.method_25394(ModsScreen.java:130)
	at net.minecraft.class_437.method_25394(class_437.java:81)
	at io.github.prospector.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:256)
	at net.minecraft.class_757.method_3192(class_757.java:603)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: me.shedaniel.clothconfig2.api.ConfigEntryBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.sargunvohra.mcmods.autoconfig1u.gui.DefaultGuiProviders.<clinit>(DefaultGuiProviders.java:36)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig$ClientOnly.<clinit>(AutoConfig.java:81)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigScreen(AutoConfig.java:71)
	at technicianlp.reauth.integration.ModMenuIntegration.lambda$getModConfigScreenFactory$0(ModMenuIntegration.java:11)
	at io.github.prospector.modmenu.ModMenu.hasConfigScreenFactory(ModMenu.java:45)
	at io.github.prospector.modmenu.gui.ModsScreen$1.method_25394(ModsScreen.java:130)
	at net.minecraft.class_437.method_25394(class_437.java:81)
	at io.github.prospector.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:256)

-- Screen render details --
Details:
	Screen name: io.github.prospector.modmenu.gui.ModsScreen
	Mouse location: Scaled: (222, 233). Absolute: (668.000000, 700.000000)
	Screen size: Scaled: (640, 318). Absolute: (1920, 954). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:603)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.4.0-42-generic
	Java Version: 14.0.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 622283216 bytes (593 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		itemscroller: Item Scroller 0.15.0-dev.20200630.022843
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		phosphor: Phosphor 0.6.0+build.7
		reauth: ReAuth 3.9.0
		sodium: Sodium 0.1.0
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.100, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9650 @ 3.00GHz
```

So, I suggest adding Cloth Config API for Fabric (which has the class `me/shedaniel/clothconfig2/api/ConfigEntryBuilder`) .

**Comment by shedaniel** [comment]
no, the mod bundling auto config should bundle cloth config instead, not us.
