### ISSUE TITLE
Does not respect symbolic links (macOS)

### ISSUE THREAD

**Issue by SmallPepperZ** [shedaniel/AutoConfig#36]
I have many MultiMC instances, and I use symbolic links so the configuration is consistent between instances. Mods using this library fail to save their config with `java.nio.file.FileAlreadyExistsException: /Applications/MultiMC.app/Contents/MacOS/instances/Fabric 1.17.0/.minecraft/config`
The full stack trace (deobfuscated by Not Enough Crashes) is below
```
[10:04:50] [Render thread/ERROR]: Failed to save config 'class squeek.appleskin.ModConfig'
me.shedaniel.autoconfig.serializer.ConfigSerializer$SerializationException: java.nio.file.FileAlreadyExistsException: /Applications/MultiMC.app/Contents/MacOS/instances/Fabric 1.17.0/.minecraft/config
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13) ~[?:?]
	at me.shedaniel.autoconfig.serializer.JanksonConfigSerializer.serialize(JanksonConfigSerializer.java:65) ~[cloth-config-5.0.34-fabric.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.save(ConfigManager.java:83) ~[cloth-config-5.0.34-fabric.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:54) ~[cloth-config-5.0.34-fabric.jar:?]
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-5.0.34-fabric.jar:?]
	at squeek.appleskin.ModConfig.init(ModConfig.java:20) ~[appleskin-fabric-mc1.17-2.0.0.jar:?]
	at squeek.appleskin.AppleSkin.onInitializeClient(AppleSkin.java:12) ~[appleskin-fabric-mc1.17-2.0.0.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34) ~[fabric-loader-0.11.6.jar:?]
	at net.minecraft.client.MinecraftClient.redirect$zoi000$catchFabricInit(MinecraftClient:7064) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:459) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:179) [intermediary-minecraft-1.17-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.nio.file.FileAlreadyExistsException: /Applications/MultiMC.app/Contents/MacOS/instances/Fabric 1.17.0/.minecraft/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:396) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:694) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:801) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:747) ~[?:?]
	at me.shedaniel.autoconfig.serializer.JanksonConfigSerializer.serialize(JanksonConfigSerializer.java:60) ~[cloth-config-5.0.34-fabric.jar:?]
	... 26 more
```

**Comment by SmallPepperZ** [comment]
Closing as it appears to duplicate #14, and was not actually related to the symbolic links
